server:
  port: ${PORT:8862}
message: Configuración de Cajero levantado en el servidor!
eureka:
  client:
    register-with-eureka: false 
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    username: root
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=UTC
  jpa:
    hibernate: 
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect
  cloud:
    config:
      uri: http://localhost:8860
