server:
  port: ${PORT:8861}
message: Configuración de Customer levantado en el servidor!
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345678
    username: postgres
    url: jdbc:postgresql://localhost:5432/crud
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://localhost:8860
