server:
  port: ${PORT:8863}
message: Configuración de Local levantado en el servidor!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    username: root
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL5Dialect
  cloud:
    config:
      uri: http://localhost:8860
