server:
  port: ${PORT:8864}
message: Configuración de Producto levantado en el servidor!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Diver
    password: 12345678
    username: root
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
      datase-platform: org.hibernate.dialect.MySQL5Dialect
  cloud:
    config:
      uri: http://localhost:8860
