server:
  port: ${PORT:8865}
message: Configuración de Proveedor levantado en el servidor!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    username: root
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect
  cloud:
    config:
      uri: http://locahost:8860
